export interface ColorVariantClasses {
  primary: string[];
  secondary: string[];
  soft: string[];
}

// All classes MUST be explicit strings - NO template literals
// This ensures Tailwind JIT content scanning detects them
export const COMPONENT_COLORS: Record<string, ColorVariantClasses> = {
  slate: {
    primary: [
      'smart:bg-slate-600',
      'smart:text-white',
      'hover:smart:bg-slate-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-slate-600',
      'dark:smart:bg-slate-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-slate-400',
      'dark:focus-visible:smart:outline-slate-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-slate-50',
      'smart:text-slate-600',
      'hover:smart:bg-slate-100',
      'dark:smart:bg-slate-500/20',
      'dark:smart:text-slate-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-slate-500/30',
    ],
  },
  gray: {
    primary: [
      'smart:bg-gray-600',
      'smart:text-white',
      'hover:smart:bg-gray-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-gray-600',
      'dark:smart:bg-gray-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-gray-400',
      'dark:focus-visible:smart:outline-gray-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-gray-50',
      'smart:text-gray-600',
      'hover:smart:bg-gray-100',
      'dark:smart:bg-gray-500/20',
      'dark:smart:text-gray-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-gray-500/30',
    ],
  },
  zinc: {
    primary: [
      'smart:bg-zinc-600',
      'smart:text-white',
      'hover:smart:bg-zinc-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-zinc-600',
      'dark:smart:bg-zinc-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-zinc-400',
      'dark:focus-visible:smart:outline-zinc-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-zinc-50',
      'smart:text-zinc-600',
      'hover:smart:bg-zinc-100',
      'dark:smart:bg-zinc-500/20',
      'dark:smart:text-zinc-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-zinc-500/30',
    ],
  },
  neutral: {
    primary: [
      'smart:bg-neutral-600',
      'smart:text-white',
      'hover:smart:bg-neutral-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-neutral-600',
      'dark:smart:bg-neutral-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-neutral-400',
      'dark:focus-visible:smart:outline-neutral-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-neutral-50',
      'smart:text-neutral-600',
      'hover:smart:bg-neutral-100',
      'dark:smart:bg-neutral-500/20',
      'dark:smart:text-neutral-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-neutral-500/30',
    ],
  },
  stone: {
    primary: [
      'smart:bg-stone-600',
      'smart:text-white',
      'hover:smart:bg-stone-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-stone-600',
      'dark:smart:bg-stone-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-stone-400',
      'dark:focus-visible:smart:outline-stone-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-stone-50',
      'smart:text-stone-600',
      'hover:smart:bg-stone-100',
      'dark:smart:bg-stone-500/20',
      'dark:smart:text-stone-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-stone-500/30',
    ],
  },
  red: {
    primary: [
      'smart:bg-red-600',
      'smart:text-white',
      'hover:smart:bg-red-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-red-600',
      'dark:smart:bg-red-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-red-400',
      'dark:focus-visible:smart:outline-red-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-red-50',
      'smart:text-red-600',
      'hover:smart:bg-red-100',
      'dark:smart:bg-red-500/20',
      'dark:smart:text-red-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-red-500/30',
    ],
  },
  orange: {
    primary: [
      'smart:bg-orange-600',
      'smart:text-white',
      'hover:smart:bg-orange-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-orange-600',
      'dark:smart:bg-orange-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-orange-400',
      'dark:focus-visible:smart:outline-orange-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-orange-50',
      'smart:text-orange-600',
      'hover:smart:bg-orange-100',
      'dark:smart:bg-orange-500/20',
      'dark:smart:text-orange-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-orange-500/30',
    ],
  },
  amber: {
    primary: [
      'smart:bg-amber-600',
      'smart:text-white',
      'hover:smart:bg-amber-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-amber-600',
      'dark:smart:bg-amber-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-amber-400',
      'dark:focus-visible:smart:outline-amber-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-amber-50',
      'smart:text-amber-600',
      'hover:smart:bg-amber-100',
      'dark:smart:bg-amber-500/20',
      'dark:smart:text-amber-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-amber-500/30',
    ],
  },
  yellow: {
    primary: [
      'smart:bg-yellow-600',
      'smart:text-white',
      'hover:smart:bg-yellow-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-yellow-600',
      'dark:smart:bg-yellow-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-yellow-400',
      'dark:focus-visible:smart:outline-yellow-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-yellow-50',
      'smart:text-yellow-600',
      'hover:smart:bg-yellow-100',
      'dark:smart:bg-yellow-500/20',
      'dark:smart:text-yellow-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-yellow-500/30',
    ],
  },
  lime: {
    primary: [
      'smart:bg-lime-600',
      'smart:text-white',
      'hover:smart:bg-lime-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-lime-600',
      'dark:smart:bg-lime-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-lime-400',
      'dark:focus-visible:smart:outline-lime-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-lime-50',
      'smart:text-lime-600',
      'hover:smart:bg-lime-100',
      'dark:smart:bg-lime-500/20',
      'dark:smart:text-lime-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-lime-500/30',
    ],
  },
  green: {
    primary: [
      'smart:bg-green-600',
      'smart:text-white',
      'hover:smart:bg-green-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-green-600',
      'dark:smart:bg-green-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-green-400',
      'dark:focus-visible:smart:outline-green-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-green-50',
      'smart:text-green-600',
      'hover:smart:bg-green-100',
      'dark:smart:bg-green-500/20',
      'dark:smart:text-green-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-green-500/30',
    ],
  },
  emerald: {
    primary: [
      'smart:bg-emerald-600',
      'smart:text-white',
      'hover:smart:bg-emerald-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-emerald-600',
      'dark:smart:bg-emerald-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-emerald-400',
      'dark:focus-visible:smart:outline-emerald-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-emerald-50',
      'smart:text-emerald-600',
      'hover:smart:bg-emerald-100',
      'dark:smart:bg-emerald-500/20',
      'dark:smart:text-emerald-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-emerald-500/30',
    ],
  },
  teal: {
    primary: [
      'smart:bg-teal-600',
      'smart:text-white',
      'hover:smart:bg-teal-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-teal-600',
      'dark:smart:bg-teal-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-teal-400',
      'dark:focus-visible:smart:outline-teal-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-teal-50',
      'smart:text-teal-600',
      'hover:smart:bg-teal-100',
      'dark:smart:bg-teal-500/20',
      'dark:smart:text-teal-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-teal-500/30',
    ],
  },
  cyan: {
    primary: [
      'smart:bg-cyan-600',
      'smart:text-white',
      'hover:smart:bg-cyan-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-cyan-600',
      'dark:smart:bg-cyan-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-cyan-400',
      'dark:focus-visible:smart:outline-cyan-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-cyan-50',
      'smart:text-cyan-600',
      'hover:smart:bg-cyan-100',
      'dark:smart:bg-cyan-500/20',
      'dark:smart:text-cyan-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-cyan-500/30',
    ],
  },
  sky: {
    primary: [
      'smart:bg-sky-600',
      'smart:text-white',
      'hover:smart:bg-sky-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-sky-600',
      'dark:smart:bg-sky-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-sky-400',
      'dark:focus-visible:smart:outline-sky-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-sky-50',
      'smart:text-sky-600',
      'hover:smart:bg-sky-100',
      'dark:smart:bg-sky-500/20',
      'dark:smart:text-sky-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-sky-500/30',
    ],
  },
  blue: {
    primary: [
      'smart:bg-blue-600',
      'smart:text-white',
      'hover:smart:bg-blue-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-blue-600',
      'dark:smart:bg-blue-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-blue-400',
      'dark:focus-visible:smart:outline-blue-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-blue-50',
      'smart:text-blue-600',
      'hover:smart:bg-blue-100',
      'dark:smart:bg-blue-500/20',
      'dark:smart:text-blue-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-blue-500/30',
    ],
  },
  indigo: {
    primary: [
      'smart:bg-indigo-600',
      'smart:text-white',
      'hover:smart:bg-indigo-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-indigo-600',
      'dark:smart:bg-indigo-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-indigo-400',
      'dark:focus-visible:smart:outline-indigo-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-indigo-50',
      'smart:text-indigo-600',
      'hover:smart:bg-indigo-100',
      'dark:smart:bg-indigo-500/20',
      'dark:smart:text-indigo-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-indigo-500/30',
    ],
  },
  violet: {
    primary: [
      'smart:bg-violet-600',
      'smart:text-white',
      'hover:smart:bg-violet-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-violet-600',
      'dark:smart:bg-violet-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-violet-400',
      'dark:focus-visible:smart:outline-violet-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-violet-50',
      'smart:text-violet-600',
      'hover:smart:bg-violet-100',
      'dark:smart:bg-violet-500/20',
      'dark:smart:text-violet-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-violet-500/30',
    ],
  },
  purple: {
    primary: [
      'smart:bg-purple-600',
      'smart:text-white',
      'hover:smart:bg-purple-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-purple-600',
      'dark:smart:bg-purple-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-purple-400',
      'dark:focus-visible:smart:outline-purple-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-purple-50',
      'smart:text-purple-600',
      'hover:smart:bg-purple-100',
      'dark:smart:bg-purple-500/20',
      'dark:smart:text-purple-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-purple-500/30',
    ],
  },
  fuchsia: {
    primary: [
      'smart:bg-fuchsia-600',
      'smart:text-white',
      'hover:smart:bg-fuchsia-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-fuchsia-600',
      'dark:smart:bg-fuchsia-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-fuchsia-400',
      'dark:focus-visible:smart:outline-fuchsia-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-fuchsia-50',
      'smart:text-fuchsia-600',
      'hover:smart:bg-fuchsia-100',
      'dark:smart:bg-fuchsia-500/20',
      'dark:smart:text-fuchsia-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-fuchsia-500/30',
    ],
  },
  pink: {
    primary: [
      'smart:bg-pink-600',
      'smart:text-white',
      'hover:smart:bg-pink-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-pink-600',
      'dark:smart:bg-pink-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-pink-400',
      'dark:focus-visible:smart:outline-pink-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-pink-50',
      'smart:text-pink-600',
      'hover:smart:bg-pink-100',
      'dark:smart:bg-pink-500/20',
      'dark:smart:text-pink-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-pink-500/30',
    ],
  },
  rose: {
    primary: [
      'smart:bg-rose-600',
      'smart:text-white',
      'hover:smart:bg-rose-500',
      'focus-visible:smart:outline-2',
      'focus-visible:smart:outline-offset-2',
      'focus-visible:smart:outline-rose-600',
      'dark:smart:bg-rose-500',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-rose-400',
      'dark:focus-visible:smart:outline-rose-500',
    ],
    secondary: [
      'smart:bg-white',
      'smart:text-gray-900',
      'smart:inset-ring',
      'smart:inset-ring-gray-300',
      'hover:smart:bg-gray-50',
      'dark:smart:bg-white/10',
      'dark:smart:text-white',
      'dark:smart:shadow-none',
      'dark:smart:inset-ring-white/5',
      'dark:hover:smart:bg-white/20',
    ],
    soft: [
      'smart:bg-rose-50',
      'smart:text-rose-600',
      'hover:smart:bg-rose-100',
      'dark:smart:bg-rose-500/20',
      'dark:smart:text-rose-400',
      'dark:smart:shadow-none',
      'dark:hover:smart:bg-rose-500/30',
    ],
  },
};
