#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm ci --prefer-offline --no-audit --progress=false --ignore-scripts

npx nx format:check

npx nx affected --target=lint --base=origin/main --head=HEAD --parallel=3
npx nx affected --target=test --base=origin/main --head=HEAD --parallel=3
npx nx affected --target=build --base=origin/main --head=HEAD --parallel=3

